CREATE DATABASE SISTEMAPIM;

USE SISTEMAPIM;

CREATE TABLE CLIENTE(
CPF_CNPJ VARCHAR (14) NOT NULL PRIMARY KEY,
NOME VARCHAR (30)NOT NULL,
CELULAR CHAR (11)NOT NULL,
CPF_RESPONSAVEL CHAR (11) NOT NULL,
EMAIL CHAR (30) NOT NULL,
CONFIRMAR_EMAIL CHAR (30) NOT NULL,
NUMERO_CONTA VARCHAR (15) NOT NULL,
CRIAR_SENHA VARCHAR (8) NOT NULL,
CONFIRMAR_SENHA VARCHAR (8) NOT NULL
);
CREATE TABLE  FUNCIONARIO(
CPF CHAR (11) NOT NULL PRIMARY KEY,
NOME VARCHAR (30)NOT NULL,
CELULAR CHAR (11) NOT NULL,
EMAIL CHAR (30) NOT NULL,
CONFIRMAR_EMAIL CHAR (30) NOT NULL,
ENDERECO CHAR (30)NOT NULL,
CTPS CHAR (11)NOT NULL,
RG VARCHAR (11)NOT NULL,
ESTADO_CIVIL VARCHAR(1)NOT NULL,
QNT_FILHOS VARCHAR (20)NOT NULL,
NOME_MAE VARCHAR (30)NOT NULL,
CRIAR_SENHA VARCHAR (8) NOT NULL,
CONFIRMAR_SENHA VARCHAR (8) NOT NULL
);